name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Check out repository
      - run: npm ci
        name: Install dependencies
      - run: npm run lint
        name: Run linter
      - run: npm run coverage
        name: Run tests and verify coverage
